name: 'Setup Node.js and pnpm'
description: 'Setup Node.js, pnpm, and install dependencies'

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 10.16.1
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash