/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfigurationPanels: typeof import('./components/ConfigurationPanels.vue')['default']
    Editor: typeof import('./components/Editor.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Panels: typeof import('./components/Panels.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
  }
}
