/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddBlockBtn: typeof import('./components/AddBlockBtn.vue')['default']
    BlockItem: typeof import('./components/BlockItem.vue')['default']
    BlocksPopover: typeof import('./components/BlocksPopover.vue')['default']
    CollapseAllIcon: typeof import('./components/CollapseAllIcon.vue')['default']
    ConfigurationHeader: typeof import('./components/ConfigurationHeader.vue')['default']
    ConfigurationPanels: typeof import('./components/ConfigurationPanels.vue')['default']
    DeviceModeSwitcher: typeof import('./components/DeviceModeSwitcher.vue')['default']
    Editor: typeof import('./components/Editor.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HeaderActionRenderer: typeof import('./components/HeaderActionRenderer.vue')['default']
    HeaderBackButton: typeof import('./components/header/BackButton.vue')['default']
    HeaderRedoButton: typeof import('./components/header/RedoButton.vue')['default']
    HeaderTitle: typeof import('./components/header/Title.vue')['default']
    HeaderUndoButton: typeof import('./components/header/UndoButton.vue')['default']
    IconAdjustmentsHorizontal: typeof import('~icons/heroicons/adjustments-horizontal')['default']
    IconArrowLeft: typeof import('~icons/heroicons/arrow-left')['default']
    IconArrowLongLeft: typeof import('~icons/heroicons/arrow-long-left')['default']
    IconArrowLongRight: typeof import('~icons/heroicons/arrow-long-right')['default']
    IconArrowUturnLeft: typeof import('~icons/heroicons/arrow-uturn-left')['default']
    IconArrowUturnRight: typeof import('~icons/heroicons/arrow-uturn-right')['default']
    IconChevronDown: typeof import('~icons/heroicons/chevron-down')['default']
    IconChevronLeft: typeof import('~icons/heroicons/chevron-left')['default']
    IconChevronRight: typeof import('~icons/heroicons/chevron-right')['default']
    IconDeviceTablet: typeof import('~icons/heroicons/device-tablet')['default']
    IconDocumentDuplicate: typeof import('~icons/heroicons/document-duplicate')['default']
    IconEllipsisVertical: typeof import('~icons/heroicons/ellipsis-vertical')['default']
    IconEye: typeof import('~icons/heroicons/eye')['default']
    IconEyeSlash: typeof import('~icons/heroicons/eye-slash')['default']
    IconLockClosed: typeof import('~icons/heroicons/lock-closed')['default']
    IconPlus: typeof import('~icons/heroicons/plus')['default']
    IconSquare3Stack3d: typeof import('~icons/heroicons/square3-stack3d')['default']
    IconSquaresPlus: typeof import('~icons/heroicons/squares-plus')['default']
    IconTrash: typeof import('~icons/heroicons/trash')['default']
    IconXMark: typeof import('~icons/heroicons/x-mark')['default']
    LayersPanel: typeof import('./components/LayersPanel.vue')['default']
    Panels: typeof import('./components/Panels.vue')['default']
    PropertiesPanel: typeof import('./components/PropertiesPanel.vue')['default']
    PropertyField: typeof import('./components/PropertyField.vue')['default']
    PropertyFieldRenderWrapper: typeof import('./components/PropertyFieldRenderWrapper.vue')['default']
    RenderFunctionWrapper: typeof import('./components/RenderFunctionWrapper.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    UiButton: typeof import('./components/ui/Button.vue')['default']
  }
}
